import { AppHeader } from "@/app/components/AppHeader";

export default function AboutPage() {
  return (
    <div className="landkoala-shell landkoala-shell-focus">
      <AppHeader />
      <main className="landkoala-static-page">
        <section className="landkoala-static-card">
          <p className="landkoala-kicker">About</p>
          <h1 className="landkoala-title">Open datasets powering LandKoala</h1>

          <section className="landkoala-static-section">
            <h2>⚠️ Important Disclaimer</h2>
            <div className="landkoala-disclaimer-box">
              <p className="landkoala-disclaimer">
                <strong>LandKoala is provided strictly for informational purposes only.</strong>
              </p>
              <p className="landkoala-disclaimer">
                This tool is not intended to provide professional business, real estate, legal, or financial advice. The analysis and recommendations generated by LandKoala are based on publicly available data and algorithmic scoring alone and should not be relied upon as the sole basis for any business, investment, or location decisions.
              </p>
              <p className="landkoala-disclaimer">
                <strong>No warranty or liability:</strong> LandKoala is provided "as is" without any guarantee, warranty, or representation of any kind, whether express or implied. We assume no responsibility or liability for:
              </p>
              <ul className="landkoala-disclaimer-list">
                <li>The accuracy, completeness, or currency of any data displayed</li>
                <li>Errors, omissions, or inaccuracies in analysis or scoring</li>
                <li>Any decisions, investments, or actions taken based on outputs from this app</li>
                <li>Any business losses, damages, or adverse outcomes resulting from use of this tool</li>
                <li>Service availability, uptime, or uninterrupted access</li>
              </ul>
              <p className="landkoala-disclaimer">
                Always conduct your own due diligence, consult with qualified professionals, and verify all data independently before making any significant business or investment decisions.
              </p>
            </div>
          </section>

          <section className="landkoala-static-section">
            <div className="landkoala-static-grid">
              <article className="landkoala-static-metric">
                <h3>OpenStreetMap Nominatim</h3>
                <p>Converts user-entered addresses into map-ready coordinates.</p>
                <small>Role: geocoding and search center placement.</small>
              </article>

              <article className="landkoala-static-metric">
                <h3>OpenStreetMap Overpass</h3>
                <p>Retrieves nearby businesses and points of interest for competition analysis.</p>
                <small>Role: competitor density and proximity signals.</small>
              </article>

              <article className="landkoala-static-metric">
                <h3>US Census ACS</h3>
                <p>Provides tract-level demographics used in baseline market scoring.</p>
                <small>Role: population and median income context.</small>
              </article>
            </div>
          </section>

          <section className="landkoala-static-section">
            <h2>Why this stack</h2>
            <ul>
              <li>Free and open for MVP and moderate usage.</li>
              <li>Strong US coverage for demographic and POI overlays.</li>
              <li>Simple API integration with transparent scoring inputs.</li>
            </ul>
          </section>

          <section className="landkoala-static-section">
            <h2>Known limitations</h2>
            <ul>
              <li>ACS values are periodic and not real-time.</li>
              <li>OSM completeness depends on local contributor coverage.</li>
              <li>Public endpoints can rate-limit under high request volume.</li>
            </ul>
          </section>

          <section className="landkoala-static-section">
            <h2>Created by</h2>
            <a
              className="landkoala-creator-link"
              href="https://x.com/chrisbcore"
              target="_blank"
              rel="noopener noreferrer"
              aria-label="Open chrisbcore on X"
            >
              <span className="landkoala-creator-name">@chrisbcore</span>
              <span className="landkoala-creator-url">x.com/chrisbcore {"->"}</span>
            </a>
          </section>
        </section>
      </main>
    </div>
  );
}
